config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'donate', to: 'donations#new', as: :donations_new
  post 'donate', to: 'donations#create', as: :donations_create

  get 'receive', to: 'recipients#new', as: :recipients_new
  post 'receive', to: 'recipients#create', as: :recipients_create

  scope '/coordinator' do
    get '/deliver', to: 'coordinator#deliver', as: :coordinator_deliver
    post '/deliver', to: 'coordinator#confirm', as: :coordinator_confirm
    get '/schedule', to: 'coordinator#schedule', as: :coordinator_schedule
    post '/schedule', to: 'coordinator#match', as: :coordinator_match
    get '/data', to: 'coordinator#data', as: :coordinator_data
  end

  scope '/donor' do
    get '/profile', to: 'donor#profile', as: :donor_profile
    put '/profile', to: 'donor#change_profile', as: :donor_profile_change
    patch '/profile', to: 'donor#upload_logo', as: :donor_profile_logo
  end

  scope '/recipient' do
    get '/profile', to: 'recipient_profiles#show', as: :recipient_profile
    put '/profile', to: 'recipient_profiles#change_profile', as: :recipient_profile_change
  end

  scope '/donation' do
    get '/cancel', to: 'donations#cancel', as: :donations_cancel
    get '/cancel_interest', to: 'recipient_profiles#cancel_interest', as: :interes_cancel
    get '/cancel_match', to: 'recipient_profiles#cancel_match', as: :match_cancel
  end

  get 'interest/create/:authentication/:recipient_id/:donation_id', to: 'create_interest#create'

  devise_for :users, :controllers => { sessions: 'sessions', registrations: 'registrations' }
  get '/users/exists', to: 'users#check_user', as: :user_exists
  put '/users/:id', to: 'users#update'

  get "unsubscribe" => "api#unsubscribe"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_org_tile.html.erb
<li class="org">
    <span data-tooltip aria-haspopup="true" class="has-tip tip-bottom radius" title="<%= description %>">
    <%= image_tag(image_path) %>
    </span>
</li>

app/views/static_pages/about.html.erb
<div id="about-image-block">
    <div class="about-image"></div>
    <div class="about-image-overlay"></div>
    <div class="about-content">
        <div class="row">
            <div class="small-8 small-centered columns">
                <h1 class="title">About Us</h1>
            </div>
        </div>
    </div>
</div>

<div class="about-mission-block">
    <div class="row">
        <div class="small-10 small-centered columns">
            <h3 class="dark-green">
                Food Shift works collaboratively with communities, businesses and governments to develop long-term sustainable solutions to reduce food waste and build more resilient communities.
            </h3>
            <p class="about">
                This disturbing reality is destructive to the environment and to the health of our communities. Each time food goes uneaten, all the resources that went into producing, processing, packaging, and transporting that food are wasted too. This means huge amounts of land, water, energy, money, and other materials are depleted unnecessarily. Wasting all this food is costly to individuals, businesses, municipalities and the environment. Given the resources demanded for food production, the increasing realities of climate change, and the fact that 1 in 6 Americans are hungry, it is critical that we shift our behaviors towards a more sustainable and efficient use of food.
            </p>
            <p class="about">
                At Food Shift, we know that food isn’t waste— it’s valuable nutrition that uses precious environmental resources and should be used to feed people in our communities. Through our events, online resources, and collaborative programs we provide guidance and promote opportunities for individuals, organizations, and businesses to use food waste reduction as a strategy that saves money, benefits the community, and alleviates strain on the environment. By trimming waste and diverting food loss we can alleviate hunger, create jobs, combat climate change, conserve natural resources, and cultivate more sustainable communities.
            </p>
            <p class="about">
                Food Shift developed this website to streamline the process of connecting surplus food with individuals in need in our community &mdash; even at home in Alameda County, over 15% of residents are food insecure.
            </p>
        </div>
    </div>
</div>

app/views/static_pages/contact.html.erb
<div id="contact-image-block">
  <div class="contact-image"></div>
  <div class="contact-image-overlay"></div>
  <div class="contact-content">
    <div class="row">
      <div class="small-8 small-centered columns">
        <h1 class="title">Contact Foodshift</h1>
      </div>
    </div>
  </div>
</div>

<div class="contact-content-block">
  <div class="row contact-block">
    <div class="small-12 medium-4 medium-offset-3 columns">
      <h2 class="contact-title">Say Hello</h2>
    </div>
    <div class="small-12 medium-4 end columns">
      <a href="mailto:info@foodshift.net" class="contact-link">info@foodshift.net</a>
    </div>
  </div>

  <div class="row contact-block">
    <div class="small-12 medium-4 medium-offset-3 columns">
      <h2 class="contact-title">Elsewhere</h2>
    </div>
    <div class="small-12 medium-4 end columns">
      <a href="https://www.facebook.com/foodshift" class="contact-link">
        <i class="fa fa-2x fa-facebook-square"></i>
      </a>
      <a href="https://twitter.com/FoodShift" class="contact-link">
        <i class="fa fa-2x fa-twitter-square"></i>
      </a>
    </div>
  </div>

  <div class="row contact-block last">
    <div class="small-12 medium-4 medium-offset-3 columns">
      <h2 class="contact-title">Visit</h2>
    </div>
    <div class="small-12 medium-4 end columns">
      <a href="https://www.google.com/maps/place/620+3rd+St,+Oakland,+CA+94607/@37.798018,-122.2757567,16z/data=!4m2!3m1!1s0x808f80b906c7b60b:0x13f30e5257a1a785" class="contact-link">
        620 3rd St.</br>
        Oakland, CA 94607
      </a>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="splash-block">
    <div class="splash-images">
        <div class="splash-image" style="background-position: center;background-image: url(<%= image_path 'landing_1.png' %>);"></div>
        <div class="splash-image" style="background-position: center;background-image: url(<%= image_path 'landing_2.png' %>);"></div>
        <div class="splash-image" style="background-position: center;background-image: url(<%= image_path 'landing_3.png' %>);"></div>
    </div>
    <div class="splash-overlay"></div>
    <div class="splash-title">
        <div class="row">
            <div class="small-12 columns">
                <h1 class="text-center">Food Shift</h1>
                <h2 class="text-center">Be a part of the movement to reduce wasted food.</h2>
                <div class="row button-row">
                    <div class="small-1 small-offset-4 columns">
                        <a href="<%= donations_new_url %>" class="right transparent-button">Donate Food</a>
                    </div>
                    <div class="small-1 small-offset-2 end columns">
                        <a href="<%= recipients_new_url %>" class="left transparent-button">Receive Food</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="full-width-off-white">
    <div class="row">
        <div class="small-12 columns">
            <h2 class="block-title text-center">How It Works</h2>
        </div>
    </div>
    <div class="row">
        <div class="small-2 small-offset-1 medium-1 medium-offset-2 columns">
            <h3 class="circle-border text-center"><i class="fa fa-heart-o"></i></h3>
        </div>
        <div class="small-8 medium-7 end columns">
            <h3><a class="dark-green" href="<%= donations_new_url %>">Donate</a></h3>
            <p>Are you a food service business with extra food? Fill in details, and we will connect you with an organization to pick up your surplus food.</p>
        </div>
    </div>
    <div class="row">
        <div class="small-2 small-offset-1 medium-1 medium-offset-2 columns">
            <h3 class="circle-border text-center"><i class="fa fa-thumbs-o-up"></i></h3>
        </div>
        <div class="small-8 medium-7 end columns">
            <h3><a class="dark-green" href="<%= recipients_new_url %>">Request</a></h3>
            <p>Does your nonprofit need extra food? Fill in information about your organization and we will notify you when food donations are available.</p>
        </div>
    </div>
    <div class="row">
        <div class="small-2 small-offset-1 medium-1 medium-offset-2 columns">
            <h3 class="circle-border text-center"><i class="fa fa-truck"></i></h3>
        </div>
        <div class="small-8 medium-7 end columns">
            <h3><a class="dark-green" href="#">Deliver</a></h3>
            <p>Food Shift's coordinators will find the best matches between donor and recipients.</p>
        </div>
    </div>
</div>

<%= javascript_include_tag "application/home" %>