config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'donate', to: 'donations#new', as: :donations_new
  post 'donate', to: 'donations#create', as: :donations_create

  get 'receive', to: 'recipients#new', as: :recipients_new
  post 'receive', to: 'recipients#create', as: :recipients_create

  scope '/coordinator' do
    get '/deliver', to: 'coordinator#deliver', as: :coordinator_deliver
    post '/deliver', to: 'coordinator#confirm', as: :coordinator_confirm
    get '/schedule', to: 'coordinator#schedule', as: :coordinator_schedule
    post '/schedule', to: 'coordinator#match', as: :coordinator_match
    get '/data', to: 'coordinator#data', as: :coordinator_data
  end

  scope '/donor' do
    get '/profile', to: 'donor#profile', as: :donor_profile
    put '/profile', to: 'donor#change_profile', as: :donor_profile_change
    patch '/profile', to: 'donor#upload_logo', as: :donor_profile_logo
  end

  scope '/recipient' do
    get '/profile', to: 'recipient_profiles#show', as: :recipient_profile
    put '/profile', to: 'recipient_profiles#change_profile', as: :recipient_profile_change
  end

  scope '/donation' do
    get '/cancel', to: 'donations#cancel', as: :donations_cancel
    get '/cancel_interest', to: 'recipient_profiles#cancel_interest', as: :interes_cancel
    get '/cancel_match', to: 'recipient_profiles#cancel_match', as: :match_cancel
  end

  get 'interest/create/:authentication/:recipient_id/:donation_id', to: 'create_interest#create'

  devise_for :users, :controllers => { sessions: 'sessions', registrations: 'registrations' }
  get '/users/exists', to: 'users#check_user', as: :user_exists
  put '/users/:id', to: 'users#update'

  get "unsubscribe" => "api#unsubscribe"

end

app/models/profiles/recipient_profile.rb
# == Schema Information
#
# Table name: recipient_profiles
#
#  id                     :integer          not null, primary key
#  created_at             :datetime
#  updated_at             :datetime
#  recipient_id           :integer
#  organization           :string(255)
#  address                :string(255)
#  org501c3               :integer
#  contact_person         :string(255)
#  contact_person_phone   :string(255)
#  hrs_of_operation       :string(255)
#  num_people_served      :string(255)
#  vehicle                :boolean
#  refrigeration          :boolean
#  notfications           :boolean
#  population_description :text
#  days_of_operation      :string(255)
#  food_types_wanted      :string(255)
#  food_types_unwanted    :string(255)
#  challenges             :text
#  longitude              :decimal(, )
#  latitude               :decimal(, )
#  contact_email          :string(255)
#  logo                   :string(255)
#  kitchen                :boolean
#
# Indexes
#
#  index_recipient_profiles_on_recipient_id  (recipient_id)
#

class RecipientProfile < ActiveRecord::Base
  belongs_to :recipient
  validates :recipient, presence: true

  # Image uploader using carrierwave
  mount_uploader :logo, LogoUploader
end

app/controllers/recipient_profiles_controller.rb
class RecipientProfilesController < ApplicationController
  helper_method :find_requested_donation,
                :find_received_donation,
                :find_donor_profile

  def change_profile
    request.format = :json
    profile = RecipientProfile.find_by(recipient_id: current_user.id)
    recipient = Recipient.find(current_user.id)
    respond_to do |format|
      if !params[:user].nil?
        recipient.update_attributes(
          params[:user].permit(
            :subscribed
          )
        )
        format.json { respond_with_bip(recipient) }
      end
      if !params[:recipient_profile].nil?
        profile.update_attributes(
          params[:recipient_profile].permit(
            :contact_person,
            :contact_email,
            :address,
            :contact_person_phone,
            :organization_number,
            :vehicle,
            :refrigeration,
            :kitchen,
            :population_description,
            :days_of_operation,
            :logo,
            :hrs_of_operation,
            :num_people_served,
            :org501c3
          )
        )
        if !params[:recipient_profile][:contact_email].nil?
          current_user.update(email: params[:recipient_profile][:contact_email])
        end
        format.json { respond_with_bip(profile) }
      end
    end
  end

  # GET /donation/cancel_interest
  def cancel_interest
    donation = Donation.find_by id: params[:format]
    interest = Interest.find_by(donation_id: donation.id, recipient_id: current_user.id)
    Interest.destroy(interest.id)
    redirect_to recipient_profile_path
  end

  # GET /donation/cancel_match
  def cancel_match
    donation = Donation.find_by id: params[:format]
    donation.update_attributes status: Donation.type_pending # should be type_new but it doesn't exist yet
    transaction = Transaction.find_by(donation_id: donation.id, recipient_id: current_user.id)
    @coordinator_id = transaction.coordinator_id
    Transaction.destroy(transaction.id)
    @recipient_ids = Recipient.where(subscribed: true).pluck(:id).delete(current_user.id)
    UserMailer.donation_available(@recipient_ids, donation).deliver
    UserMailer.match_canceled_donor(donation).deliver
    UserMailer.match_canceled_recipient(donation, current_user.id).deliver
    redirect_to recipient_profile_path
  end

  def show
    @user = current_user
    @profile = RecipientProfile.find_by(recipient_id: current_user.id)
    @received_donations = Transaction.where(recipient_id: current_user.id)
    @requested_donations = Interest.where(recipient_id: current_user.id)
    @total_count = @received_donations.count + @requested_donations.count
    @transactions = Transaction.where(recipient_id: current_user.id).includes(
      donation: { donor: :donor_profile }
    )
    gon.transactions = @transactions.as_json(
      include: [{ donation: {
        include: [{ donor: {
          include: [:donor_profile]
        } }]
      } }]
    )

    @interests = Interest.where(recipient_id: current_user.id).includes(
      donation: { donor: :donor_profile }
    )
    gon.interests = @interests.as_json(
      include: [{ donation: {
        include: [{ donor: {
          include: [:donor_profile]
        } }]
      } }]
    )
  end

  def find_requested_donation(donation_id)
    @interest_id = Interest.where(id: donation_id).first.donation_id
    @donation = Donation.where(id: @interest_id).first
    @donation
  end

  def find_received_donation(donation_id)
    @transaction_id = Transaction.where(id: donation_id).first.donation_id
    @donation = Donation.where(id: @transaction_id).first
    @donation
  end

  def find_donor_profile(donation_id)
    @donor_id = Donation.where(id: donation_id).first.donor_id
    @donor = DonorProfile.where(donor_id: @donor_id).first
    @donor
  end
end

app/views/recipient_profiles/_donation_item.html.erb
<div class="row">
  <div class="small-9 columns">
    <h4><%= donation.description %></h4>
    <b>Donated By:</b> <%= find_donor_profile(donation.id).person %>
    <% if donation.status == Donation.type_completed %>
      <br> <b>Picked up at:</b> <%= find_transaction(donation.id).picked_up_at.strftime("%I:%M %p %A, %B %d, %Y") %> <br>
      <b>Delivered at:</b> <%= find_transaction(donation.id).delivered_at.strftime("%I:%M %p %A, %B %d, %Y") %> <br>
    <% end %>
  </div>
  <div class="small-3 columns">
    <div class="donation-modify">
      <% if donation.status == Donation.type_completed %> 
        <span class="donation-status">Received</span> 
      <% elsif donation.status == Donation.type_pending %>
        <span class="donation-status">Requested</span> <br>
        <%= link_to "Cancel Request", interest_cancel_path(donation), data: {confirm: "Are you sure you want to cancel your donation request?"}, class: "donation-modify-link donation-cancel" %>
      <% elsif donation.status == Donation.type_in_progress %>
        <span class="donation-status">Matched</span> <br>
        <%= link_to "Cancel", match_cancel_path(donation), data: {confirm: "Are you sure you no longer want to receive this donation?"}, class: "donation-modify-link donation-cancel" %>
      <% elsif donation.status == Donation.type_canceled %>
        <span class="donation-status">Canceled</span>
      <% end %>
    </div>
  </div>
</div>

app/views/recipient_profiles/show.html.erb
<div class="donor-dashboard-block">
  <div class="row">
    <div class="small-12 columns">
      <div class="dashboard-wrap">
        <div class="dashboard">
          <div class="card-header">
            <div class="row">
              <div class="small-12 columns">
                <span class="card-header-title">Welcome, <%= @user.email %> (User ID: <%= @user.id %>)</span>
              </div>
            </div>
          </div>
          <div class="card-profile">
            <div class="row">
              <div class="small-12 columns">
                <div class="profile-info">
                  <div class="row">
                    <div class="medium-4 columns">
                      <div class="profile-img-wrap">
                        <div class="profile-img-trigger"><%= image_tag @profile.logo.thumb, class: "profile-img" %></div>
                        <div class="profile-img-target">
                          <%= simple_form_for @profile, :html => { :id => "profile-img-submit" } do |f| %>
                            <%= f.file_field :logo, class: "profile-img-uploader" %>
                          <% end %>
                        </div>
                      </div>
                      <h1 class="profile-info-title"><%= best_in_place @profile, :organization, as: :input %></h1>
                    </div>
                    <div class="medium-8 columns">
                      <div class="row">
                        <div class="medium-6 columns">
                          <ul class="fa-ul">
                            <li><i class="fa-li fa fa-user"></i><%= best_in_place @profile, :contact_person, as: :input %></li>
                            <li><i class="fa-li fa fa-phone"></i><%= best_in_place @profile, :contact_person_phone, as: :input %></li>
                            <li><i class="fa-li fa fa-envelope"></i><%= best_in_place @profile, :contact_email, as: :input %></li>
                            <li><i class="fa-li fa fa-map-marker"></i><%= best_in_place @profile, :address, as: :input %></li>
                          </ul>
                        </div>
                        <div class="medium-6 columns">
                          <h2 class="profile-summary-title">Donation Summary</h2>
                          <ul class="profile-summary-wrap">
                            <li class="profile-summary-item">Matched: <span class="profile-summary-count"><%= @received_donations.count %></span></li>
                            <li class="profile-summary-item">Requested: <span class="profile-summary-count"><%= @requested_donations.count %></span></li>
                          </ul>
                        </div>
                      </div>
                      <div class="row">
                        <div class="medium-11 columns">
                          <dl class="accordion" data-accordion>
                            <dd class="accordion-navigation">
                              <a href="#panel1a">Additional Information</a>
                              <div id="panel1a" class="content">
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Subscribed?</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @user, :subscribed, :as => :checkbox, :class => "additional-info-value", :url => recipient_profile_change_path %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">501(c)(3) number:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :org501c3, as: :input, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Hours of operation:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :hrs_of_operation, as: :input, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Days of operation:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :days_of_operation, as: :input, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Average number of people served:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :num_people_served, as: :input, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Food types wanted:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :food_types_wanted, as: :input, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Food types unwanted:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :food_types_unwanted, as: :input, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Challenges faced:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :challenges, as: :input, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Population description:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :population_description, as: :input, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Refrigeration:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :refrigeration, :as => :checkbox, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Vehicle:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :vehicle, :as => :checkbox, :class => "additional-info-value" %>
                                  </div>
                                </div>
                                <div class="row additional-info">
                                  <div class="small-6 columns">
                                    <span class="additional-info-key">Kitchen:</span>
                                  </div>
                                  <div class="small-6 columns">
                                    <%= best_in_place @profile, :kitchen, :as => :checkbox, :class => "additional-info-value" %>
                                  </div>
                                </div>
                              </div>
                            </dd>
                          </dl>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div id="recipient-history" class="history"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag "react_components/recipient/profile" %>