config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'donate', to: 'donations#new', as: :donations_new
  post 'donate', to: 'donations#create', as: :donations_create

  get 'receive', to: 'recipients#new', as: :recipients_new
  post 'receive', to: 'recipients#create', as: :recipients_create

  scope '/coordinator' do
    get '/deliver', to: 'coordinator#deliver', as: :coordinator_deliver
    post '/deliver', to: 'coordinator#confirm', as: :coordinator_confirm
    get '/schedule', to: 'coordinator#schedule', as: :coordinator_schedule
    post '/schedule', to: 'coordinator#match', as: :coordinator_match
    get '/data', to: 'coordinator#data', as: :coordinator_data
  end

  scope '/donor' do
    get '/profile', to: 'donor#profile', as: :donor_profile
    put '/profile', to: 'donor#change_profile', as: :donor_profile_change
    patch '/profile', to: 'donor#upload_logo', as: :donor_profile_logo
  end

  scope '/recipient' do
    get '/profile', to: 'recipient_profiles#show', as: :recipient_profile
    put '/profile', to: 'recipient_profiles#change_profile', as: :recipient_profile_change
  end

  scope '/donation' do
    get '/cancel', to: 'donations#cancel', as: :donations_cancel
    get '/cancel_interest', to: 'recipient_profiles#cancel_interest', as: :interes_cancel
    get '/cancel_match', to: 'recipient_profiles#cancel_match', as: :match_cancel
  end

  get 'interest/create/:authentication/:recipient_id/:donation_id', to: 'create_interest#create'

  devise_for :users, :controllers => { sessions: 'sessions', registrations: 'registrations' }
  get '/users/exists', to: 'users#check_user', as: :user_exists
  put '/users/:id', to: 'users#update'

  get "unsubscribe" => "api#unsubscribe"

end

app/views/layouts/_footer.html.erb
<div class="footer footer-contain-to-grid">
    <div class="row">
      <div class="small-6 columns">
        <a class="title" href="http://foodshift.net/"><img id="fs-logo" src="<%= asset_path 'logo.png' %>"></img></a>

      </div>
      <div class="small-6 columns">
          <div class="right" id="bp-wrapper">
              <a href="http://www.calblueprint.org">
                <span class="powered-by">Powered by</span>
                <img class="spinner" id="bp-logo" src="<%= asset_path 'bp_logo_small.png' %>"></img>
              </a>
          </div>
      </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="nav-contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
      <h1><%= link_to("Food Shift", root_url) %></h1>
      </li>
      <li class="divider"></li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li class=""><%= link_to("About", about_path) %></li>
        <li class="divider"></li>
        <li class=""><%= link_to("Contact", contact_path) %></li>
        <li class="divider"></li>
        <% if user_signed_in? %>
          <li class="">
          <% if current_user.type == User.type_donor %>
            <%= link_to 'View Profile', donor_profile_path %>
          <% elsif current_user.type == User.type_recipient %>
            <%= link_to 'View Profile', recipient_profile_path %>
          <% elsif current_user.type == User.type_coordinator %>
            <%= link_to 'View Dashboard', coordinator_schedule_path %>
          <% end %>
          </li>
          <li class="divider"></li>
          <li class=""><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li class=""><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/_notifications.html.erb
<% if !flash_toastr_msgs.empty? %>
<script>
    <% flash_toastr_msgs.each do |type, msg| %>
    toastr.<%= type %>('<%= msg %>');
    <% end %>
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag 'favicon.ico' %>

    <title><%= content_for?(:title) ? yield(:title) : "Food Shift" %></title>

    <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.6/slick.css' %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,800' %>
    <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.0/css/toastr.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/underscore.string/2.3.3/underscore.string.min.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.0/js/toastr.min.js" %>

    <%= csrf_meta_tags %>

    <%= include_gon %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= render 'layouts/notifications' %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.6/slick.min.js" %>
  </body>
</html>